#===============================================================================
#
# 'core' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================

default_CPPopt          = -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Qsox- -DTRACING
debug_CPPopt            = -c -nologo -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Qsox- -DTRACING


core_cppobjs =                                                                 \
    _default\Core.obj                                                          \
    _default\CoreMain.obj                                                      \
    _default\DDrawError.obj                                                    \
    _default\File.obj                                                          \
    _default\FileSystem.obj                                                    \
    _default\Font.obj                                                          \
    _default\Image.obj                                                         \
    _default\Keyboard.obj                                                      \
    _default\Mouse.obj                                                         \
    _default\ParamSet.obj                                                      \
    _default\ResourcePack.obj                                                  \
    _default\Sprite.obj                                                        \
    _default\Surface.obj                                                       \
    _default\VideoCard.obj                                                     \
    _default\ZipFile.obj                                                       \


_default\core.lib       : __before_all__ $(core_cppobjs) 
                          
                          lib.exe                                              \
                          -debugtype:cv                                        \
                          -out:_default\core.lib                               \
                          $(core_cppobjs) 
                          

__before_all__          : 
                          if not exist _default mkdir _default


#-------------------------------------------------------------------------------
#
#   'Core.cpp'

Core_cpp__files =                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\Core.obj       : Core.cpp $(Core_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Core.cpp


#-------------------------------------------------------------------------------
#
#   'CoreMain.cpp'

CoreMain_cpp__files =                                                          \
    Win32Error.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    VideoCard.hpp                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    Surface.hpp                                                                \
    Keyboard.hpp                                                               \
    Event.hpp                                                                  \
    Application.hpp                                                            \
    Mouse.hpp                                                                  \
    Window.hpp                                                                 \

_default\CoreMain.obj   : CoreMain.cpp $(CoreMain_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ CoreMain.cpp


#-------------------------------------------------------------------------------
#
#   'DDrawError.cpp'

DDrawError_cpp__files =                                                        \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \

_default\DDrawError.obj : DDrawError.cpp $(DDrawError_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ DDrawError.cpp


#-------------------------------------------------------------------------------
#
#   'File.cpp'

File_cpp__files =                                                              \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\File.obj       : File.cpp $(File_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ File.cpp


#-------------------------------------------------------------------------------
#
#   'FileSystem.cpp'

FileSystem_cpp__files =                                                        \
    FileSystem.hpp                                                             \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ZipFile.hpp                                                                \

_default\FileSystem.obj : FileSystem.cpp $(FileSystem_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ FileSystem.cpp


#-------------------------------------------------------------------------------
#
#   'Font.cpp'

Font_cpp__files =                                                              \
    Font.hpp                                                                   \
    ParamSet.hpp                                                               \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\Font.obj       : Font.cpp $(Font_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Font.cpp


#-------------------------------------------------------------------------------
#
#   'Image.cpp'

Image_cpp__files =                                                             \
    Image.hpp                                                                  \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_default\Image.obj      : Image.cpp $(Image_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Image.cpp


#-------------------------------------------------------------------------------
#
#   'Keyboard.cpp'

Keyboard_cpp__files =                                                          \
    Keyboard.hpp                                                               \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    Event.hpp                                                                  \

_default\Keyboard.obj   : Keyboard.cpp $(Keyboard_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Keyboard.cpp


#-------------------------------------------------------------------------------
#
#   'Mouse.cpp'

Mouse_cpp__files =                                                             \
    Mouse.hpp                                                                  \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\Mouse.obj      : Mouse.cpp $(Mouse_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Mouse.cpp


#-------------------------------------------------------------------------------
#
#   'ParamSet.cpp'

ParamSet_cpp__files =                                                          \
    ParamSet.hpp                                                               \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\ParamSet.obj   : ParamSet.cpp $(ParamSet_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ ParamSet.cpp


#-------------------------------------------------------------------------------
#
#   'ResourcePack.cpp'

ResourcePack_cpp__files =                                                      \
    ResourcePack.hpp                                                           \
    FileSystem.hpp                                                             \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ZipFile.hpp                                                                \
    Image.hpp                                                                  \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_default\ResourcePack.obj: ResourcePack.cpp $(ResourcePack_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ ResourcePack.cpp


#-------------------------------------------------------------------------------
#
#   'Sprite.cpp'

Sprite_cpp__files =                                                            \
    Sprite.hpp                                                                 \
    Image.hpp                                                                  \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_default\Sprite.obj     : Sprite.cpp $(Sprite_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Sprite.cpp


#-------------------------------------------------------------------------------
#
#   'Surface.cpp'

Surface_cpp__files =                                                           \
    Surface.hpp                                                                \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\Surface.obj    : Surface.cpp $(Surface_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ Surface.cpp


#-------------------------------------------------------------------------------
#
#   'VideoCard.cpp'

VideoCard_cpp__files =                                                         \
    VideoCard.hpp                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    Surface.hpp                                                                \

_default\VideoCard.obj  : VideoCard.cpp $(VideoCard_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ VideoCard.cpp


#-------------------------------------------------------------------------------
#
#   'ZipFile.cpp'

ZipFile_cpp__files =                                                           \
    ZipFile.hpp                                                                \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_default\ZipFile.obj    : ZipFile.cpp $(ZipFile_cpp__files)
                          icl.exe $(default_CPPopt) -Fo_default/ ZipFile.cpp

