#===============================================================================
#
# 'core' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================

default_CPPopt          = -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Qsox- -DTRACING
debug_CPPopt            = -c -nologo -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Qsox- -DTRACING


core_cppobjs =                                                                 \
    _debug\Core.obj                                                            \
    _debug\CoreMain.obj                                                        \
    _debug\DDrawError.obj                                                      \
    _debug\File.obj                                                            \
    _debug\FileSystem.obj                                                      \
    _debug\Font.obj                                                            \
    _debug\Image.obj                                                           \
    _debug\Keyboard.obj                                                        \
    _debug\Mouse.obj                                                           \
    _debug\ParamSet.obj                                                        \
    _debug\ResourcePack.obj                                                    \
    _debug\Sprite.obj                                                          \
    _debug\Surface.obj                                                         \
    _debug\VideoCard.obj                                                       \
    _debug\ZipFile.obj                                                         \


_debug\core.lib         : __before_all__ $(core_cppobjs) 
                          
                          lib.exe                                              \
                          -out:_debug\core.lib                                 \
                          $(core_cppobjs) 
                          

__before_all__          : 
                          if not exist _debug mkdir _debug


#-------------------------------------------------------------------------------
#
#   'Core.cpp'

Core_cpp__files =                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\Core.obj         : Core.cpp $(Core_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Core.cpp


#-------------------------------------------------------------------------------
#
#   'CoreMain.cpp'

CoreMain_cpp__files =                                                          \
    Win32Error.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    VideoCard.hpp                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    Surface.hpp                                                                \
    Keyboard.hpp                                                               \
    Application.hpp                                                            \
    Mouse.hpp                                                                  \
    Window.hpp                                                                 \

_debug\CoreMain.obj     : CoreMain.cpp $(CoreMain_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ CoreMain.cpp


#-------------------------------------------------------------------------------
#
#   'DDrawError.cpp'

DDrawError_cpp__files =                                                        \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \

_debug\DDrawError.obj   : DDrawError.cpp $(DDrawError_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ DDrawError.cpp


#-------------------------------------------------------------------------------
#
#   'File.cpp'

File_cpp__files =                                                              \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\File.obj         : File.cpp $(File_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ File.cpp


#-------------------------------------------------------------------------------
#
#   'FileSystem.cpp'

FileSystem_cpp__files =                                                        \
    FileSystem.hpp                                                             \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ZipFile.hpp                                                                \

_debug\FileSystem.obj   : FileSystem.cpp $(FileSystem_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ FileSystem.cpp


#-------------------------------------------------------------------------------
#
#   'Font.cpp'

Font_cpp__files =                                                              \
    Font.hpp                                                                   \
    ParamSet.hpp                                                               \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\Font.obj         : Font.cpp $(Font_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Font.cpp


#-------------------------------------------------------------------------------
#
#   'Image.cpp'

Image_cpp__files =                                                             \
    Image.hpp                                                                  \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_debug\Image.obj        : Image.cpp $(Image_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Image.cpp


#-------------------------------------------------------------------------------
#
#   'Keyboard.cpp'

Keyboard_cpp__files =                                                          \
    Keyboard.hpp                                                               \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\Keyboard.obj     : Keyboard.cpp $(Keyboard_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Keyboard.cpp


#-------------------------------------------------------------------------------
#
#   'Mouse.cpp'

Mouse_cpp__files =                                                             \
    Mouse.hpp                                                                  \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\Mouse.obj        : Mouse.cpp $(Mouse_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Mouse.cpp


#-------------------------------------------------------------------------------
#
#   'ParamSet.cpp'

ParamSet_cpp__files =                                                          \
    ParamSet.hpp                                                               \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\ParamSet.obj     : ParamSet.cpp $(ParamSet_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ ParamSet.cpp


#-------------------------------------------------------------------------------
#
#   'ResourcePack.cpp'

ResourcePack_cpp__files =                                                      \
    ResourcePack.hpp                                                           \
    FileSystem.hpp                                                             \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ZipFile.hpp                                                                \
    Image.hpp                                                                  \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_debug\ResourcePack.obj : ResourcePack.cpp $(ResourcePack_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ ResourcePack.cpp


#-------------------------------------------------------------------------------
#
#   'Sprite.cpp'

Sprite_cpp__files =                                                            \
    Sprite.hpp                                                                 \
    Image.hpp                                                                  \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    ImageFormat.hpp                                                            \
    Surface.hpp                                                                \

_debug\Sprite.obj       : Sprite.cpp $(Sprite_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Sprite.cpp


#-------------------------------------------------------------------------------
#
#   'Surface.cpp'

Surface_cpp__files =                                                           \
    Surface.hpp                                                                \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\Surface.obj      : Surface.cpp $(Surface_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ Surface.cpp


#-------------------------------------------------------------------------------
#
#   'VideoCard.cpp'

VideoCard_cpp__files =                                                         \
    VideoCard.hpp                                                              \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \
    Surface.hpp                                                                \

_debug\VideoCard.obj    : VideoCard.cpp $(VideoCard_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ VideoCard.cpp


#-------------------------------------------------------------------------------
#
#   'ZipFile.cpp'

ZipFile_cpp__files =                                                           \
    ZipFile.hpp                                                                \
    File.hpp                                                                   \
    Core.hpp                                                                   \
    DDrawError.hpp                                                             \
    Exception.hpp                                                              \
    Msg.hpp                                                                    \
    Win32error.hpp                                                             \
    DInputError.hpp                                                            \
    Type.hpp                                                                   \
    Vector.hpp                                                                 \
    Rect.hpp                                                                   \

_debug\ZipFile.obj      : ZipFile.cpp $(ZipFile_cpp__files)
                          icl.exe $(debug_CPPopt) -Fo_debug/ ZipFile.cpp

