#===============================================================================
#
# 'tdemo' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================



tdemo_cppobjs =                                                                \
    _optimized\Asteroid.obj                                                    \
    _optimized\BackgroundGenerator.obj                                         \
    _optimized\Explosion.obj                                                   \
    _optimized\Nebula.obj                                                      \
    _optimized\Missile.obj                                                     \
    _optimized\PlayerShip.obj                                                  \
    _optimized\Rasterizer.obj                                                  \
    _optimized\Scaner.obj                                                      \
    _optimized\SpaceObject.obj                                                 \
    _optimized\Star.obj                                                        \
    _optimized\StarField.obj                                                   \
    _optimized\Tdemo.obj                                                       \


_optimized\tdemo.exe    : __before_all__ $(tdemo_cppobjs) 
                          
                          link.exe                                             \
                          -opt:ref                                             \
                          -defaultlib:user32.lib                               \
                          -defaultlib:gdi32.lib                                \
                          -defaultlib:winmm.lib                                \
                          -defaultlib:dinput.lib                               \
                          -defaultlib:ddraw.lib                                \
                          -defaultlib:dxguid.lib                               \
                          -defaultlib:..\..\sys\_default\core.lib              \
                          -defaultlib:..\..\sys\_default\vfx.lib               \
                          -defaultlib:..\..\sys\_default\gui.lib               \
                          -subsystem:windows                                   \
                          -out:_optimized\tdemo.exe                            \
                          $(tdemo_cppobjs) 
                          

__before_all__          : 
                          if not exist _optimized mkdir _optimized


#-------------------------------------------------------------------------------
#
#   'Asteroid.cpp'

Asteroid_cpp__files =                                                          \
    Asteroid.hpp                                                               \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_optimized\Asteroid.obj : Asteroid.cpp $(Asteroid_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Asteroid.cpp


#-------------------------------------------------------------------------------
#
#   'BackgroundGenerator.cpp'

BackgroundGenerator_cpp__files =                                               \
    BackgroundGenerator.hpp                                                    \
    ..\..\sys\Type.hpp                                                         \
    StarField.hpp                                                              \
    ..\..\sys\PixelShader.hpp                                                  \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \
    Nebula.hpp                                                                 \

_optimized\BackgroundGenerator.obj: BackgroundGenerator.cpp $(BackgroundGenerator_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        BackgroundGenerator.cpp


#-------------------------------------------------------------------------------
#
#   'Explosion.cpp'

Explosion_cpp__files =                                                         \
    Explosion.hpp                                                              \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_optimized\Explosion.obj: Explosion.cpp $(Explosion_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Explosion.cpp


#-------------------------------------------------------------------------------
#
#   'Nebula.cpp'

Nebula_cpp__files =                                                            \
    Nebula.hpp                                                                 \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\PixelShader.hpp                                                  \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\FixedPoint.hpp                                                   \
    ..\..\sys\BitOps.hpp                                                       \

_optimized\Nebula.obj   : Nebula.cpp $(Nebula_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Nebula.cpp


#-------------------------------------------------------------------------------
#
#   'Missile.cpp'

Missile_cpp__files =                                                           \
    Missile.hpp                                                                \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_optimized\Missile.obj  : Missile.cpp $(Missile_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Missile.cpp


#-------------------------------------------------------------------------------
#
#   'PlayerShip.cpp'

PlayerShip_cpp__files =                                                        \
    PlayerShip.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_optimized\PlayerShip.obj: PlayerShip.cpp $(PlayerShip_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        PlayerShip.cpp


#-------------------------------------------------------------------------------
#
#   'Rasterizer.cpp'

Rasterizer_cpp__files =                                                        \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \

_optimized\Rasterizer.obj: Rasterizer.cpp $(Rasterizer_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Rasterizer.cpp


#-------------------------------------------------------------------------------
#
#   'Scaner.cpp'

Scaner_cpp__files =                                                            \
    Scaner.hpp                                                                 \
    ..\..\sys\WidgetView.hpp                                                   \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Font.hpp                                                         \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\BitOps.hpp                                                       \

_optimized\Scaner.obj   : Scaner.cpp $(Scaner_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Scaner.cpp


#-------------------------------------------------------------------------------
#
#   'SpaceObject.cpp'

SpaceObject_cpp__files =                                                       \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_optimized\SpaceObject.obj: SpaceObject.cpp $(SpaceObject_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        SpaceObject.cpp


#-------------------------------------------------------------------------------
#
#   'Star.cpp'

Star_cpp__files =                                                              \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \

_optimized\Star.obj     : Star.cpp $(Star_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Star.cpp


#-------------------------------------------------------------------------------
#
#   'StarField.cpp'

StarField_cpp__files =                                                         \
    StarField.hpp                                                              \
    ..\..\sys\PixelShader.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \

_optimized\StarField.obj: StarField.cpp $(StarField_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        StarField.cpp


#-------------------------------------------------------------------------------
#
#   'Tdemo.cpp'

Tdemo_cpp__files =                                                             \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Tune.hpp                                                         \
    tdemo.hpp                                                                  \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\Font.hpp                                                         \
    ..\..\sys\GUImanager.hpp                                                   \
    ..\..\sys\WidgetView.hpp                                                   \
    ..\..\sys\Sprite.hpp                                                       \
    Asteroid.hpp                                                               \
    SpaceObject.hpp                                                            \
    Explosion.hpp                                                              \
    Missile.hpp                                                                \
    PlayerShip.hpp                                                             \
    BackgroundGenerator.hpp                                                    \
    StarField.hpp                                                              \
    ..\..\sys\PixelShader.hpp                                                  \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\BitOps.hpp                                                       \
    Scaner.hpp                                                                 \

_optimized\Tdemo.obj    : Tdemo.cpp $(Tdemo_cpp__files)
                          icl.exe -c -GR -GX -O3 -Og -QxM -QaxM -Oi -Qunroll                         -Qwn3 -Qwd 985 -Fo_optimized/ -Fa_optimized/ -FAcs                        Tdemo.cpp

