#===============================================================================
#
# 'tdemo' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================



tdemo_cppobjs =                                                                \
    _debug\Asteroid.obj                                                        \
    _debug\BackgroundGenerator.obj                                             \
    _debug\Explosion.obj                                                       \
    _debug\GlareStar.obj                                                       \
    _debug\Nebula.obj                                                          \
    _debug\Missile.obj                                                         \
    _debug\PlayerShip.obj                                                      \
    _debug\Rasterizer.obj                                                      \
    _debug\Scaner.obj                                                          \
    _debug\SpaceObject.obj                                                     \
    _debug\Star.obj                                                            \
    _debug\StarField.obj                                                       \
    _debug\Tdemo.obj                                                           \


_debug\tdemo.exe        : __before_all__ $(tdemo_cppobjs) 
                          
                          link.exe                                             \
                          -debug                                               \
                          -debugtype:cv                                        \
                          -opt:ref                                             \
                          -defaultlib:user32.lib                               \
                          -defaultlib:gdi32.lib                                \
                          -defaultlib:winmm.lib                                \
                          -defaultlib:dinput.lib                               \
                          -defaultlib:ddraw.lib                                \
                          -defaultlib:dxguid.lib                               \
                          -defaultlib:..\..\sys\_debug\core.lib                \
                          -defaultlib:..\..\sys\_debug\vfx.lib                 \
                          -defaultlib:..\..\sys\_debug\gui.lib                 \
                          -subsystem:windows                                   \
                          -out:tdemo.exe                                       \
                          $(tdemo_cppobjs) 
                          

__before_all__          : 
                          if not exist _debug mkdir _debug


#-------------------------------------------------------------------------------
#
#   'Asteroid.cpp'

Asteroid_cpp__files =                                                          \
    Asteroid.hpp                                                               \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_debug\Asteroid.obj     : Asteroid.cpp $(Asteroid_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Asteroid.cpp


#-------------------------------------------------------------------------------
#
#   'BackgroundGenerator.cpp'

BackgroundGenerator_cpp__files =                                               \
    BackgroundGenerator.hpp                                                    \
    ..\..\sys\Type.hpp                                                         \
    StarField.hpp                                                              \
    ..\..\sys\NoiseLayer.hpp                                                   \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \
    GlareStar.hpp                                                              \
    Nebula.hpp                                                                 \
    ..\..\sys\PixelShader.hpp                                                  \

_debug\BackgroundGenerator.obj: BackgroundGenerator.cpp $(BackgroundGenerator_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        BackgroundGenerator.cpp


#-------------------------------------------------------------------------------
#
#   'Explosion.cpp'

Explosion_cpp__files =                                                         \
    Explosion.hpp                                                              \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_debug\Explosion.obj    : Explosion.cpp $(Explosion_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Explosion.cpp


#-------------------------------------------------------------------------------
#
#   'GlareStar.cpp'

GlareStar_cpp__files =                                                         \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    GlareStar.hpp                                                              \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \

_debug\GlareStar.obj    : GlareStar.cpp $(GlareStar_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        GlareStar.cpp


#-------------------------------------------------------------------------------
#
#   'Nebula.cpp'

Nebula_cpp__files =                                                            \
    Nebula.hpp                                                                 \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\PixelShader.hpp                                                  \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\FixedPoint.hpp                                                   \
    ..\..\sys\BitOps.hpp                                                       \

_debug\Nebula.obj       : Nebula.cpp $(Nebula_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Nebula.cpp


#-------------------------------------------------------------------------------
#
#   'Missile.cpp'

Missile_cpp__files =                                                           \
    Missile.hpp                                                                \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_debug\Missile.obj      : Missile.cpp $(Missile_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Missile.cpp


#-------------------------------------------------------------------------------
#
#   'PlayerShip.cpp'

PlayerShip_cpp__files =                                                        \
    PlayerShip.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_debug\PlayerShip.obj   : PlayerShip.cpp $(PlayerShip_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        PlayerShip.cpp


#-------------------------------------------------------------------------------
#
#   'Rasterizer.cpp'

Rasterizer_cpp__files =                                                        \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \

_debug\Rasterizer.obj   : Rasterizer.cpp $(Rasterizer_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Rasterizer.cpp


#-------------------------------------------------------------------------------
#
#   'Scaner.cpp'

Scaner_cpp__files =                                                            \
    Scaner.hpp                                                                 \
    ..\..\sys\WidgetView.hpp                                                   \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Font.hpp                                                         \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\BitOps.hpp                                                       \

_debug\Scaner.obj       : Scaner.cpp $(Scaner_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Scaner.cpp


#-------------------------------------------------------------------------------
#
#   'SpaceObject.cpp'

SpaceObject_cpp__files =                                                       \
    SpaceObject.hpp                                                            \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \

_debug\SpaceObject.obj  : SpaceObject.cpp $(SpaceObject_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        SpaceObject.cpp


#-------------------------------------------------------------------------------
#
#   'Star.cpp'

Star_cpp__files =                                                              \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \

_debug\Star.obj         : Star.cpp $(Star_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Star.cpp


#-------------------------------------------------------------------------------
#
#   'StarField.cpp'

StarField_cpp__files =                                                         \
    StarField.hpp                                                              \
    ..\..\sys\NoiseLayer.hpp                                                   \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \

_debug\StarField.obj    : StarField.cpp $(StarField_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        StarField.cpp


#-------------------------------------------------------------------------------
#
#   'Tdemo.cpp'

Tdemo_cpp__files =                                                             \
    ..\..\sys\Random.hpp                                                       \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Tune.hpp                                                         \
    tdemo.hpp                                                                  \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\ParamSet.hpp                                                     \
    ..\..\sys\Font.hpp                                                         \
    ..\..\sys\GUImanager.hpp                                                   \
    ..\..\sys\WidgetView.hpp                                                   \
    ..\..\sys\Sprite.hpp                                                       \
    Asteroid.hpp                                                               \
    SpaceObject.hpp                                                            \
    Explosion.hpp                                                              \
    Missile.hpp                                                                \
    PlayerShip.hpp                                                             \
    BackgroundGenerator.hpp                                                    \
    StarField.hpp                                                              \
    ..\..\sys\NoiseLayer.hpp                                                   \
    ..\..\sys\Noise.hpp                                                        \
    ..\..\sys\FixedPoint.hpp                                                   \
    Star.hpp                                                                   \
    Rasterizer.hpp                                                             \
    ..\..\sys\BitOps.hpp                                                       \
    Scaner.hpp                                                                 \

_debug\Tdemo.obj        : Tdemo.cpp $(Tdemo_cpp__files)
                          icl.exe -c -GR -GX -Od -Zi -Qwn3 -Qwd 985 -Fo_debug/ -Qsox-                        -DTRACING                        Tdemo.cpp

