#===============================================================================
#
# 'dwig' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================



dwig_cppobjs =                                                                 \
    _default\Bout.obj                                                          \
    _default\DwigApp.obj                                                       \
    _default\MainMenu.obj                                                      \
    _default\InitialState.obj                                                  \
    _default\Clip.obj                                                          \
    _default\Cursor.obj                                                        \
    _default\Indicator.obj                                                     \
    _default\Matrix.obj                                                        \
    _default\View.obj                                                          \
    _default\ClipView.obj                                                      \
    _default\CursorView.obj                                                    \
    _default\IndicatorView.obj                                                 \
    _default\JumperView.obj                                                    \


_default\               : __before_all__ $(dwig_cppobjs) 
                          
                          link.exe                                             \
                          -opt:ref                                             \
                          -debugtype:cv                                        \
                          -debug                                               \
                          -defaultlib:user32.lib                               \
                          -defaultlib:gdi32.lib                                \
                          -defaultlib:dinput.lib                               \
                          -defaultlib:ddraw.lib                                \
                          -defaultlib:dxguid.lib                               \
                          -defaultlib:..\..\sys\_default\core.lib              \
                          -defaultlib:..\..\sys\_default\vfx.lib               \
                          -defaultlib:..\..\sys\_default\gui.lib               \
                          -subsystem:windows                                   \
                          -out:dwig.exe                                        \
                          $(dwig_cppobjs) 
                          

__before_all__          : 
                          if not exist _default mkdir _default


#-------------------------------------------------------------------------------
#
#   'Bout.cpp'

Bout_cpp__files =                                                              \
    ..\..\sys\Render2D.hpp                                                     \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Fill.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \
    DwigApp.hpp                                                                \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Event.hpp                                                        \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Sprite.hpp                                                       \
    Matrix.hpp                                                                 \
    Clip.hpp                                                                   \
    Cursor.hpp                                                                 \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \

_default\Bout.obj       : Bout.cpp $(Bout_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ Bout.cpp


#-------------------------------------------------------------------------------
#
#   'DwigApp.cpp'

DwigApp_cpp__files =                                                           \
    DwigApp.hpp                                                                \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Event.hpp                                                        \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Sprite.hpp                                                       \
    Matrix.hpp                                                                 \
    Clip.hpp                                                                   \
    Cursor.hpp                                                                 \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \

_default\DwigApp.obj    : DwigApp.cpp $(DwigApp_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ DwigApp.cpp


#-------------------------------------------------------------------------------
#
#   'MainMenu.cpp'

MainMenu_cpp__files =                                                          \
    DwigApp.hpp                                                                \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Event.hpp                                                        \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Sprite.hpp                                                       \
    Matrix.hpp                                                                 \
    Clip.hpp                                                                   \
    Cursor.hpp                                                                 \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \

_default\MainMenu.obj   : MainMenu.cpp $(MainMenu_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ MainMenu.cpp


#-------------------------------------------------------------------------------
#
#   'InitialState.cpp'

InitialState_cpp__files =                                                      \
    DwigApp.hpp                                                                \
    ..\..\sys\Application.hpp                                                  \
    ..\..\sys\VideoCard.hpp                                                    \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Keyboard.hpp                                                     \
    ..\..\sys\Event.hpp                                                        \
    ..\..\sys\Mouse.hpp                                                        \
    ..\..\sys\Window.hpp                                                       \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\ZipFile.hpp                                                      \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Sprite.hpp                                                       \
    Matrix.hpp                                                                 \
    Clip.hpp                                                                   \
    Cursor.hpp                                                                 \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \

_default\InitialState.obj: InitialState.cpp $(InitialState_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ InitialState.cpp


#-------------------------------------------------------------------------------
#
#   'Clip.cpp'

Clip_cpp__files =                                                              \
    Clip.hpp                                                                   \
    ..\..\sys\Vector.hpp                                                       \

_default\Clip.obj       : Clip.cpp $(Clip_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ Clip.cpp


#-------------------------------------------------------------------------------
#
#   'Cursor.cpp'

Cursor_cpp__files =                                                            \
    Cursor.hpp                                                                 \
    ..\..\sys\Vector.hpp                                                       \
    Matrix.hpp                                                                 \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\ZipFile.hpp                                                      \
    Clip.hpp                                                                   \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \

_default\Cursor.obj     : Cursor.cpp $(Cursor_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ Cursor.cpp


#-------------------------------------------------------------------------------
#
#   'Indicator.cpp'

Indicator_cpp__files =                                                         \
    Indicator.hpp                                                              \
    SchemeElement.hpp                                                          \
    Clip.hpp                                                                   \
    ..\..\sys\Vector.hpp                                                       \

_default\Indicator.obj  : Indicator.cpp $(Indicator_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ Indicator.cpp


#-------------------------------------------------------------------------------
#
#   'Matrix.cpp'

Matrix_cpp__files =                                                            \
    ..\..\sys\Render2D.hpp                                                     \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\Fill.hpp                                                         \
    ..\..\sys\BitOps.hpp                                                       \
    Matrix.hpp                                                                 \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\ResourcePack.hpp                                                 \
    ..\..\sys\FileSystem.hpp                                                   \
    ..\..\sys\ZipFile.hpp                                                      \
    Clip.hpp                                                                   \
    Cursor.hpp                                                                 \
    SchemeElement.hpp                                                          \
    View.hpp                                                                   \
    Jumper.hpp                                                                 \
    Indicator.hpp                                                              \
    ClipView.hpp                                                               \
    CursorView.hpp                                                             \
    IndicatorView.hpp                                                          \
    JumperView.hpp                                                             \

_default\Matrix.obj     : Matrix.cpp $(Matrix_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ Matrix.cpp


#-------------------------------------------------------------------------------
#
#   'View.cpp'

View_cpp__files =                                                              \
    View.hpp                                                                   \
    ..\..\sys\Surface.hpp                                                      \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \

_default\View.obj       : View.cpp $(View_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ View.cpp


#-------------------------------------------------------------------------------
#
#   'ClipView.cpp'

ClipView_cpp__files =                                                          \
    ClipView.hpp                                                               \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    View.hpp                                                                   \
    Clip.hpp                                                                   \

_default\ClipView.obj   : ClipView.cpp $(ClipView_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ ClipView.cpp


#-------------------------------------------------------------------------------
#
#   'CursorView.cpp'

CursorView_cpp__files =                                                        \
    CursorView.hpp                                                             \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    View.hpp                                                                   \
    Cursor.hpp                                                                 \

_default\CursorView.obj : CursorView.cpp $(CursorView_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ CursorView.cpp


#-------------------------------------------------------------------------------
#
#   'IndicatorView.cpp'

IndicatorView_cpp__files =                                                     \
    IndicatorView.hpp                                                          \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    View.hpp                                                                   \
    Indicator.hpp                                                              \
    SchemeElement.hpp                                                          \
    Clip.hpp                                                                   \

_default\IndicatorView.obj: IndicatorView.cpp $(IndicatorView_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ IndicatorView.cpp


#-------------------------------------------------------------------------------
#
#   'JumperView.cpp'

JumperView_cpp__files =                                                        \
    JumperView.hpp                                                             \
    ..\..\sys\Sprite.hpp                                                       \
    ..\..\sys\Image.hpp                                                        \
    ..\..\sys\File.hpp                                                         \
    ..\..\sys\Core.hpp                                                         \
    ..\..\sys\DDrawError.hpp                                                   \
    ..\..\sys\Exception.hpp                                                    \
    ..\..\sys\Msg.hpp                                                          \
    ..\..\sys\Win32error.hpp                                                   \
    ..\..\sys\DInputError.hpp                                                  \
    ..\..\sys\Type.hpp                                                         \
    ..\..\sys\Vector.hpp                                                       \
    ..\..\sys\Rect.hpp                                                         \
    ..\..\sys\ImageFormat.hpp                                                  \
    ..\..\sys\Surface.hpp                                                      \
    View.hpp                                                                   \
    Jumper.hpp                                                                 \
    SchemeElement.hpp                                                          \
    Clip.hpp                                                                   \

_default\JumperView.obj : JumperView.cpp $(JumperView_cpp__files)
                          icl.exe -c -nologo -GR -GX -O2 -Qwn3 -Qwd 985 -Fo_default/ JumperView.cpp

