#===============================================================================
#
# 'test' project MAKEFILE
# generated by gen_makefile 1.1 (c) Ghost Dragon 2001
#
#===============================================================================

CPPopt                  = -c -O2 -Qansi


test_cppobjs =                                                                 \
    _normal\s1.obj                                                             \
    _normal\s2.obj                                                             \


tst.exe                 : __before_all__ $(test_cppobjs) 
                          cd .\_normal
                          link.exe                                             \
                          -defaultlib:user32.lib                               \
                          -debugtype:cv                                        \
                          $(test_cppobjs) 
                          cd ..

__before_all__          : 
                          if not exist _normal mkdir _normal


#-------------------------------------------------------------------------------
#
#   's1.cpp'

s1_cpp__files =                                                                \

_normal\s1.obj          : s1.cpp $(s1_cpp__files)
                          icl $(CPPopt) -Fo_normal/ s1.cpp


#-------------------------------------------------------------------------------
#
#   's2.cpp'

s2_cpp__files =                                                                \

_normal\s2.obj          : s2.cpp $(s2_cpp__files)
                          icl $(CPPopt) -Fo_normal/ s2.cpp

